Repository WildCodeSchool/orleans-0918-php-ohterroir, pull requests merged in 2018-10, with the labels that each got.

#1 SP01_US01 NavBar faite
  .gitignore
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/favicon.png
  public/assets/images/iconMenuBurger.png
  public/assets/images/logo_OhTerroir.png
  src/Controller/HomeController.php
  src/View/Admin/add.html.twig
  src/View/Home/home.html.twig
  src/View/Item/index.html.twig
  src/View/Partenaires/_form.html.twig
  src/View/edit.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
  src/View/show.html.twig
Labels: Changes requested, Corrections done

#2 SPRINT01_US01_NAVBAR validé sur DEV
  .gitignore
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/favicon.png
  public/assets/images/iconMenuBurger.png
  public/assets/images/logo_OhTerroir.png
  src/Controller/HomeController.php
  src/View/Admin/add.html.twig
  src/View/Home/home.html.twig
  src/View/Item/index.html.twig
  src/View/Partenaires/_form.html.twig
  src/View/edit.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
  src/View/show.html.twig
Labels: Reviewed by PO

#3 Sprint01 us02 diaporama
  app/db.php.dist
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/devanture.jpg
  public/assets/images/interieur.jpg
  public/assets/images/low_contrast_linen_@2X.png
  public/assets/images/paper.png
  public/assets/images/tables.jpg
  public/assets/images/terrasse.jpg
  src/Controller/HomeController.php
  src/View/layout.html.twig
  src/View/slideShow.html.twig
Labels: Corrections done

#5 Sprint02 us41 navbar admin
  app/routing.php
  src/Controller/HomeAdminController.php
  src/View/Admin/home.html.twig
  src/View/headerAdmin.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#10 FIX_9_ Bug_CSS
  public/assets/css/styles.css
Labels: Reviewed by PO

#12 SPRINT01_US03_Localisation
  data/oh_terroir_2018_contactDetails.sql
  public/assets/css/styles.css
  public/assets/images/label_AB.jpg
  src/Controller/HomeController.php
  src/Model/ContactDetails.php
  src/Model/ContactDetailsManager.php
  src/View/ContactsDetails.html.twig
  src/View/Home/home.html.twig
  src/View/_form.html.twig
Labels: Corrections done, Reviewed by PO

#19 SPRINT01_US03_LOCALISATION validé sur dev
  data/oh_terroir_2018_contactDetails.sql
  public/assets/css/styles.css
  public/assets/images/label_AB.jpg
  src/Controller/HomeController.php
  src/Model/ContactDetails.php
  src/Model/ContactDetailsManager.php
  src/View/ContactsDetails.html.twig
  src/View/Home/home.html.twig
  src/View/_form.html.twig
Labels: Reviewed by PO

#14 SPRINT02_US08_Section 3 banniere producteurs
  public/assets/css/styles.css
  public/assets/images/produits-bio-produits-locaux.png
  src/View/Home/bannerGrower.html.twig
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#17 SPRINT01_US11_NAVIGATION_FOOTER
  public/assets/css/styles.css
  src/View/Home/home.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#15 SPRINT02_US20 page carte section1
  app/routing.php
  public/assets/css/styles.css
  src/Controller/DishesController.php
  src/View/dishes.html.twig
  src/View/header.html.twig
Labels: Corrections done, Reviewed by PO

#20 DEV to MASTER
  app/routing.php
  data/oh_terroir_2018_schedule.sql
  data/oh_terroir_2018_weekdays.sql
  public/assets/css/styles.css
  public/assets/images/produits-bio-produits-locaux.png
  src/Controller/DishesController.php
  src/Controller/HomeController.php
  src/Model/Schedule.php
  src/Model/ScheduleManager.php
  src/View/ContactsDetails.html.twig
  src/View/Home/bannerGrower.html.twig
  src/View/Home/home.html.twig
  src/View/dishes.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#22 Sprint02 us05 home page section 2 categories plats
  data/oh_terroir_2018_dishCategory.sql
  public/assets/css/styles.css
  public/assets/images/categories/1.jpg
  public/assets/images/categories/2.jpg
  public/assets/images/categories/3.jpg
  public/assets/images/categories/4.jpg
  src/Controller/HomeController.php
  src/Model/DishCategory.php
  src/Model/DishCategoryManager.php
  src/View/Home/categoriesHomeShow.html.twig
  src/View/Home/home.html.twig
Labels: Corrections done, Reviewed by PO

#25 Dev sur Master
  data/oh_terroir_2018_dishCategory.sql
  public/assets/css/styles.css
  public/assets/images/categories/1.jpg
  public/assets/images/categories/2.jpg
  public/assets/images/categories/3.jpg
  public/assets/images/categories/4.jpg
  src/Controller/HomeController.php
  src/Model/DishCategory.php
  src/Model/DishCategoryManager.php
  src/View/Home/categoriesHomeShow.html.twig
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#16 SPRINT02_US42_COORDONNEES Admin
  app/routing.php
  public/assets/css/styles.css
  src/Controller/ContactDetailsController.php
  src/Controller/HomeAdminController.php
  src/Model/ContactDetails.php
  src/Model/ContactDetailsManager.php
  src/View/Admin/contactDetails.html.twig
  src/View/layoutAdmin.html.twig
Labels: Corrections done, Reviewed by PO

#23 SPRINT01_US13_LOCALISATION_FOOTER
  public/assets/css/styles.css
  public/assets/images/terrasse_footer.jpg
  src/View/footer.html.twig
Labels: Corrections done, Reviewed by PO

#28 Dev to Master
  public/assets/css/styles.css
  public/assets/images/terrasse_footer.jpg
  src/View/footer.html.twig
Labels: Reviewed by PO

#29 SPRINT01_US10_LOCALISATION_FOOTER
  public/assets/css/styles.css
  src/View/footer.html.twig
Labels: Reviewed by PO

#32 Dev to Master
  public/assets/css/styles.css
  src/View/footer.html.twig
Labels: Reviewed by PO

#27 SPRINT03_US30_PRESENTATION_PAGE_PRODUCTEURS_SECTION_1
  app/routing.php
  public/assets/css/styles.css
  src/Controller/GrowerController.php
  src/View/Grower/show.html.twig
  src/View/header.html.twig
Labels: Corrections done, Reviewed by PO

#37 Fix 36 problemes footer navbar
  public/assets/css/styles.css
  src/Controller/DishesController.php
  src/Controller/GrowerController.php
  src/View/footer.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#18 SPRINT02_US06_HOME_PAGE_SECTION_2 Affichage section "Offres Spéciales"
  data/oh_terroir_2018_specialOffer.sql
  public/assets/css/styles.css
  public/assets/images/id-card.png
  public/assets/images/ticket.png
  src/Controller/HomeController.php
  src/Model/SpecialOffer.php
  src/Model/SpecialOfferManager.php
  src/View/Home/home.html.twig
  src/View/specialOffers.html.twig
Labels: Corrections done, Reviewed by PO

#24 SPRINT02_US07_HOME PAGE SECTION 3 avis tripAdvisor
  src/View/Home/tripAdvisor.html.twig
Labels: Corrections done, Reviewed by PO

#39 Fix 38 edition coordonnees admin
  app/routing.php
  src/Model/ContactDetails.php
Labels: Corrections done, Reviewed by PO

#41 FIX_40_PB_MERGE_TRIPADVISOR
  data/oh_terroir_2018_opinionTripAdvisor.sql
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/Model/OpinionTripAdvisor.php
  src/Model/OpinionTripAdvisorManager.php
  src/View/Home/home.html.twig
Labels: Conflicts done, Reviewed by PO

#30 SPRINT03 US44 AFFICHAGE COORDONNEES_ Admin
  app/routing.php
  src/Controller/ContactDetailsController.php
  src/Model/ContactDetailsManager.php
  src/View/Admin/contactDetailsShow.html.twig
  src/View/headerAdmin.html.twig
Labels: Corrections done, Reviewed by PO

#31 Sprint02 us51 categories plats
  app/routing.php
  public/assets/css/styles.css
  src/Controller/DishCategoryController.php
  src/Model/DishCategory.php
  src/Model/DishCategoryManager.php
  src/View/Admin/addDishCategory.html.twig
Labels: Conflicts done, Reviewed by PO

#43 Dev to Master
  app/routing.php
  data/oh_terroir_2018_opinionTripAdvisor.sql
  data/oh_terroir_2018_specialOffer.sql
  public/assets/css/styles.css
  public/assets/images/id-card.png
  public/assets/images/ticket.png
  src/Controller/ContactDetailsController.php
  src/Controller/DishCategoryController.php
  src/Controller/HomeController.php
  src/Model/ContactDetails.php
  src/Model/ContactDetailsManager.php
  src/Model/DishCategory.php
  src/Model/DishCategoryManager.php
  src/Model/OpinionTripAdvisor.php
  src/Model/OpinionTripAdvisorManager.php
  src/Model/SpecialOffer.php
  src/Model/SpecialOfferManager.php
  src/View/Admin/addDishCategory.html.twig
  src/View/Admin/contactDetailsShow.html.twig
  src/View/Home/home.html.twig
  src/View/Home/tripAdvisor.html.twig
  src/View/headerAdmin.html.twig
  src/View/specialOffers.html.twig
Labels: Reviewed by PO

#42 Sprint03 us21 categories plats section 2.1
  data/oh_terroir_2018_dishCategory.sql
  public/assets/css/styles.css
  public/assets/images/categories/fullsize/1-fs.jpg
  public/assets/images/categories/fullsize/2-fs.jpg
  public/assets/images/categories/fullsize/3-fs.jpg
  public/assets/images/categories/fullsize/4-fs.jpg
  public/assets/images/minus_sign-circle.png
  public/assets/images/plus_sign-circle.png
  src/Controller/DishesController.php
  src/View/dishes.html.twig
Labels: Conflicts done, Reviewed by PO

#45 Dev to Master
  data/oh_terroir_2018_dishCategory.sql
  public/assets/css/styles.css
  public/assets/images/categories/fullsize/1-fs.jpg
  public/assets/images/categories/fullsize/2-fs.jpg
  public/assets/images/categories/fullsize/3-fs.jpg
  public/assets/images/categories/fullsize/4-fs.jpg
  public/assets/images/minus_sign-circle.png
  public/assets/images/plus_sign-circle.png
  src/Controller/DishesController.php
  src/View/dishes.html.twig
Labels: Reviewed by PO
