Repository WildCodeSchool/orleans-0918-php-ohterroir, pull requests merged in 2018-11, with the labels that each got.

#46 SPRINT04 US50 CATEGORIES PLATS LISTE ADMIN
  app/routing.php
  public/assets/css/styles.css
  src/Controller/DishCategoryController.php
  src/View/Admin/dishCategory.html.twig
  src/View/headerAdmin.html.twig
Labels: Conflicts done, Reviewed by PO

#48 SPRINT05_US9_HOME_PAGE_SECTION_2_FOURCHETTE_PRIX
  src/Controller/DishesController.php
  src/Controller/HomeController.php
  src/Model/DishCategoryManager.php
  src/View/Home/categoriesHomeShow.html.twig
Labels: Reviewed by PO

#47 SPRINT04_US33_FORMULAIRE_CONTACT_PRODUCTEURS
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/styles.css
  src/Controller/GrowerController.php
  src/View/Grower/formContact.html.twig
  src/View/Grower/show.html.twig
Labels: Conflicts done, Reviewed by PO

#57 FIX_55_PSR_TRAVIS_SUR_DEV
  src/Model/DishCategoryManager.php
  src/Model/OpinionTripAdvisorManager.php
Labels: Reviewed by PO

#54 Dev to Master
  app/routing.php
  composer.json
  composer.lock
  data/oh_terroir_2018_growerCategory.sql
  public/assets/css/styles.css
  src/Controller/DishCategoryController.php
  src/Controller/DishesController.php
  src/Controller/GrowerController.php
  src/Controller/HomeController.php
  src/Model/DishCategoryManager.php
  src/Model/GrowerCategory.php
  src/Model/GrowerCategoryManager.php
  src/Model/OpinionTripAdvisorManager.php
  src/View/Admin/dishCategory.html.twig
  src/View/Grower/formContact.html.twig
  src/View/Grower/growerCategories.html.twig
  src/View/Grower/show.html.twig
  src/View/Home/categoriesHomeShow.html.twig
  src/View/header.html.twig
  src/View/headerAdmin.html.twig
Labels: Reviewed by PO

#53 FIX_49_CSS_HOME_PAGE_ET_LIENS_NAVBAR
  public/assets/css/styles.css
  public/assets/images/id-card.png
  public/assets/images/ticket.png
  src/View/Home/bannerGrower.html.twig
  src/View/Home/categoriesHomeShow.html.twig
  src/View/Home/tripAdvisor.html.twig
  src/View/header.html.twig
  src/View/specialOffers.html.twig
Labels: Reviewed by PO

#58 Sprint05 us32 page producteurs section 2.2
  data/oh_terroir_2018_grower.sql
  public/assets/css/styles.css
  src/Controller/GrowerController.php
  src/Model/Grower.php
  src/Model/GrowerManager.php
  src/View/Grower/grower.html.twig
  src/View/Grower/growerCategories.html.twig
Labels: Reviewed by PO

#51 SPRINT04_US22_PAGE_CARTE_2.2_SSCATEGORIES_PLATS
  data/oh_terroir_2018_dish.sql
  data/oh_terroir_2018_dishSubcategory.sql
  public/assets/css/styles.css
  src/Controller/DishesController.php
  src/Model/Dish.php
  src/Model/DishManager.php
  src/View/dishes.html.twig
Labels: Conflicts done, Reviewed by PO

#60 Sprint05 us53 categories plats modification categorie de plat
  app/routing.php
  src/Controller/DishCategoryController.php
  src/Model/DishCategoryManager.php
  src/View/Admin/dishCategory.html.twig
  src/View/Admin/editDishCategory.html.twig
Labels: Corrections done, Reviewed by PO

#59 FIX_56_AFFICHAGE_ADRESSE_ET_HORAIRES
  data/oh_terroir_2018_schedule.sql
  public/assets/css/styles.css
  public/assets/images/60-lines.png
  src/Controller/DishesController.php
  src/Controller/GrowerController.php
  src/Controller/HomeController.php
  src/Model/ContactDetails.php
  src/Service/ScheduleService.php
  src/View/ContactsDetails.html.twig
Labels: Conflicts done, Reviewed by PO

#66 SPRINT05_US24_FOUCHETTE_PRIX_PAGE_CATEGORIE
  src/View/dishes.html.twig
Labels: Reviewed by PO

#65 FIX_63_GLOBAL_CSS_HTML
  public/assets/css/styles.css
  src/View/Grower/formContact.html.twig
  src/View/Grower/grower.html.twig
  src/View/Home/categoriesHomeShow.html.twig
  src/View/dishes.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#68 Dev to Master
  public/assets/css/styles.css
  src/View/Grower/formContact.html.twig
  src/View/Grower/grower.html.twig
  src/View/Home/categoriesHomeShow.html.twig
  src/View/dishes.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#69 FIX_67_ADMIN_CATEGORIES_PLAT_UPDATE
  src/Controller/DishCategoryController.php
  src/Model/DishCategoryManager.php
  src/View/Admin/editDishCategory.html.twig
Labels: Reviewed by PO

#70 FIX_62_FOOTER + MENTIONS LEGALES
  app/routing.php
  public/assets/css/styles.css
  src/Controller/GrowerController.php
  src/Controller/LegalNoticeController.php
  src/View/footer.html.twig
  src/View/layout.html.twig
  src/View/legalNotice.html.twig
Labels: Reviewed by PO

#73 FIX_72_GOOGLE_MAP
  src/View/footer.html.twig
Labels: Reviewed by PO

#71 Dev to Master
  app/routing.php
  public/assets/css/styles.css
  src/Controller/DishCategoryController.php
  src/Controller/GrowerController.php
  src/Controller/LegalNoticeController.php
  src/Model/DishCategoryManager.php
  src/View/Admin/editDishCategory.html.twig
  src/View/footer.html.twig
  src/View/layout.html.twig
  src/View/legalNotice.html.twig
Labels: Reviewed by PO

#76 Dev to Master
  src/View/header.html.twig
Labels: Reviewed by PO
